# -*- coding: utf-8 -*-
"""Spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTZkYEwKMUbhV-UsSmSSFVdjusjZpXDC
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df=pd.read_csv('/content/mail_data.csv')





print(df)

df.isnull()

df.shape

df.loc[df['Category']=='spam','Category',]=0
df.loc[df['Category']=='ham','Category',]=1

print(df)

df=df.where((pd.notnull(df)),'')

df.shape

x=df.Message
y=df.Category
print(x)

print(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

print(x.shape)
print(x_train.shape)
print(x_test.shape)

print(y.shape)
print(y_train.shape)
print(y_test.shape)

feature_extraction =TfidfVectorizer(min_df= 1,stop_words='english',lowercase=True)
x_train_features=feature_extraction.fit_transform(x_train)
x_test_feature=feature_extraction.transform(x_test)
y_train=y_train.astype('int')
y_test=y_test.astype('int')

print(x_train_features)

model=LogisticRegression()

model.fit(x_train_features,y_train)

prediction_on_training_data=model.predict(x_train_features)
accuracy_on_training_data=accuracy_score(y_train,prediction_on_training_data)

print('Accuracy on training data : ', accuracy_on_training_data)

prediction_on_test_data =model.predict(x_test_feature)
accuracy_on_test_data=accuracy_score(y_test,prediction_on_test_data)

print('Accuracy on test data : ', accuracy_on_test_data)

input_mail=["Hey amujuri,As your mentor, i'm excited to share incredible news with you  Brace yourself for an remarkable journey as coding as ningas proudly presentys its first ever batch of java"]
input_data_feature=feature_extraction.transform(input_mail)
prediction=model.predict(input_data_feature)
print(prediction)

if(prediction[0]==1):
   print("Ham mail")
else:
  print("Spam mail")

